sudo: required
dist: trusty
language: node_js
node_js:
- '6'
addons:
  chrome: stable
before_install:
  - npm install -g npm@5
install:
  - npm install
before_script:
- npm run test
script:
- ./ci/build.sh
deploy:
- provider: script
  script: ci/travis-deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ (^(master|release).*$)"
env:
  global:
  - NODE_VERSION=6.10.0